[package]
name = "backtest"
version = "0.1.0"
edition = "2024"

[dependencies]
kalshi-rs = "0.2.1"
regex = "1.11.1"
serde = {version="1.0.219", features=["derive"]}
serde_json = "1.0.140"
statrs = "0.18.0"
chrono = "0.4"
